create table if not exists dw.fct_inventory (
    inventory_id bigint generated by default as identity primary key,
    product_id bigint not null references dw.dim_product(product_id),
    stock_on_hand numeric(18,4) not null default 0,
    updated_at timestamptz default timezone('utc', now())
);

create index if not exists idx_fct_inventory_product on dw.fct_inventory(product_id);
